# Generated by Django 4.2.23 on 2025-07-18 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='tasks',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
