# Generated by Django 4.2.23 on 2025-07-18 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_tasks_created_at_remove_tasks_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tasktags',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='tasktags',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='tasktags',
            name='task',
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
        migrations.DeleteModel(
            name='TaskTags',
        ),
    ]
